In [5]:
import numpy as np
import warnings
from Activations import Activation
warnings.filterwarnings("ignore")

In [2]:
# input_data x1,x2
import numpy as np
x1 = np.random.randint(50,80,10)
x2 = np.random.randint(160,180,10)
X = np.c_[x1,x2]

In [3]:
w1 = np.random.randn(1)
w2 = np.random.randn(1)

In [4]:
out_w1 = w1*x1
out_w2 = w2*x2

In [5]:
out = np.c_[out_w1,out_w2]
out

array([[-120.32044157,  213.27413754],
       [-114.20245302,  210.80854057],
       [-157.0283729 ,  198.48055575],
       [-152.94971386,  203.41174968],
       [-108.08446446,  213.27413754],
       [-146.83172531,  200.94615271],
       [-122.35977109,  198.48055575],
       [-146.83172531,  207.11014513],
       [-134.5957482 ,  210.80854057],
       [-144.79239579,  218.20533147]])

In [6]:
w2

array([1.23279848])

In [30]:
y.reshape(-1,1)

array([[0],
       [0],
       [2],
       [1],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2]])

In [8]:
#one_hot -- keras.utils.to_categorical(data)
y = np.random.randint(0,5,100)

In [11]:
##data
def make_onehot(x):
    col = np.unique(x).size
    row = x.size
    data = np.zeros((row,col))
    for i in np.arange(row):
        data[i,x[i]] = 1
    return data

In [17]:
## 
from sklearn.datasets import load_iris
X = load_iris()['data']
y = load_iris()['target']

In [58]:
X.shape

(150, 4)

In [56]:
y = y.reshape(-1,1)

In [57]:
y.shape

(150, 1)

In [59]:
W = np.random.randn(4,1)
b = np.random.randn(1)

In [60]:
y_hat = np.dot(X,W) + b

In [12]:
## y onehot
y = make_onehot(y)

In [13]:
print(X.shape)
print(y.shape)

(150, 4)
(150, 3)


In [14]:
W = np.random.randn(4,3)
b = np.random.randn(3)

In [15]:
Activation.softmax(np.dot(X,W) + b)

array([[0.91813414, 0.00923423, 0.07263163],
       [0.82588953, 0.03173677, 0.1423737 ],
       [0.88113627, 0.01568035, 0.10318338],
       [0.80247259, 0.01799778, 0.17952963],
       [0.92593924, 0.00635653, 0.06770422],
       [0.94514998, 0.00520696, 0.04964306],
       [0.90223823, 0.00966847, 0.0880933 ],
       [0.88279328, 0.01112281, 0.10608391],
       [0.77275549, 0.0267121 , 0.2005324 ],
       [0.79650449, 0.01924756, 0.18424795],
       [0.93316221, 0.0066051 , 0.06023269],
       [0.84781913, 0.00913405, 0.14304682],
       [0.79868297, 0.02388873, 0.17742831],
       [0.8571773 , 0.01676943, 0.12605328],
       [0.97911213, 0.00382364, 0.01706424],
       [0.98428367, 0.00152101, 0.01419532],
       [0.97430608, 0.00523985, 0.02045406],
       [0.92869978, 0.01106335, 0.06023687],
       [0.93449325, 0.00749221, 0.05801454],
       [0.94386481, 0.00459073, 0.05154446],
       [0.85458297, 0.01508553, 0.13033149],
       [0.94431822, 0.00734783, 0.04833396],
       [0.

In [70]:
x = np.array([1,2,3])
np.exp(x)/np.sum(np.exp(x))

array([0.09003057, 0.24472847, 0.66524096])

In [19]:
def mse(y,t):
    return np.sum((y-t)**2)*0.5

In [20]:
y = np.random.randn(10)
t = np.random.randn(10)
mse(y,t)

7.8376458028469065

In [19]:
def cross_entropy(y,t):
    epsilon = 1e-7
    y = Activation.softmax(y)
    return -np.sum(t*np.log(y+epsilon))/y.shape[0]

In [50]:
y = np.array([1,7,0])
t = np.array([0,1,0])
x1  =cross_entropy(y,t)

In [51]:
y = np.array([2,4,6])
t = np.array([0,0,1])
x2 = cross_entropy(y,t)


In [53]:
def der(f,x):
    h = 1e-7
    fxh = f(x+h)
    fx = f(x)
    return (fxh - fx)/h

In [54]:
f = lambda x:x**2 +2*x

In [59]:
def ff(x,y):
    return x**2 + y**2

In [58]:
der(함수,3)

8.00000009348878

In [75]:
def fx(x):
    return x[0]**2+x[1]**2

In [123]:
def par_der(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x)
        x[idx] = float(tmp_val) - h
        fxh2 = f(x)
        grad[idx] = (fxh1 - fxh2)/(2*h)
        x[idx] = tmp_val
        it.iternext()
    return grad

In [125]:
x = np.array([3.,4.])
par_der(fx,x)

array([6., 8.])

In [134]:
x = np.random.randn(5,6)
it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
while not it.finished:
    x[it.multi_index]
    it.iternext()

In [18]:
def numerical_gradient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)
        x[idx] = tmp_val - h
        fxh2 = f(x)
        grad[idx] = (fxh1-fxh2)/(2*h)
        x[idx] = tmp_val
        it.iternext()
    return grad

In [137]:
def function_2d(x):
    return x[0]**2+x[1]**2

In [138]:
x = np.array([2.,3.])
function_2d(x)

13.0

In [139]:
numerical_gradient(function_2d,x)

array([4., 6.])

In [140]:
from sklearn.datasets import load_iris

In [141]:
X = load_iris()['data']
y = load_iris()['target']

In [143]:
y = make_onehot(y)

In [154]:
X.shape

(150, 4)

In [155]:
W1 = np.random.randn(4,10)
b1 = np.random.randn(10)
W2 = np.random.randn(10,5)
b2 = np.random.randn(5)
W3 = np.random.randn(5,3)
b3 = np.random.randn(3)

In [206]:
layer1 = np.dot(X,W1) + b1
z1 = Activation.relu(layer1)
layer2 = np.dot(z1,W2) + b2
z2 = Activation.relu(layer2)
layer3 = np.dot(z2,W3) + b3
output = Activation.softmax(layer3)

In [233]:
#cross_entropy(y,output)
loss = cross_entropy
f = lambda w : loss(y,output)
dw = numerical_gradient(f,W1)

In [15]:
class Network:
    
    def __init__(self):
        self.W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3)
        }
        self.b = {
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3)
        }
        self.Activation ={
            'sigmoid':Activation.sigmoid,
            'relu':Activation.relu,
            'softmax':Activation.softmax
        }
        
    
    def predict(self,x):
        result = np.dot(x,self.W['W1']) + self.b['b1']
        for i in range(len(self.W)-2):
            result = np.dot(result,self.W['W'+str(i+2)]) + self.b['b'+str(i+2)]
            result = Activation.relu(result)    
        result = np.dot(result,self.W['W'+str(len(self.W))]) + self.b['b'+str(len(self.W))]    
        return Activation.softmax(result)
    
    def loss(self,x,t):
        self.y = self.predict(x)
        loss = cross_entropy(self.y,t)
        return loss
    
    def gradient(self,x,t,learning_rate):
        self.learning_rate = learning_rate
        f = lambda w : self.loss(x,t)
        for i in range(len(self.W)):
            self.W['W'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.W['W'+str(i+1)])
            self.b['b'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.b['b'+str(i+1)])
            

        
    
    def accuracy(self,x,t):
        result = self.predict(x)
        acc = sum(np.argmax(result,axis=1) == np.argmax(t,axis=1))/len(t)
        return acc
        

In [20]:
model = Network()
X = load_iris()['data']
y = load_iris()['target']
y = make_onehot(y)

In [21]:
a = model.predict(X)

In [22]:
b = model.predict(X)

In [23]:
%%time
epochs = 100
for epoch in range(epochs):
    epoch += 1
    model.gradient(X,y,1e-3)
    print("epoch",epoch,\
          "loss====",model.loss(X,y),"accuracy====",model.accuracy(X,y))

epoch 1 loss==== 0.8400005474907304 accuracy==== 0.7133333333333334
epoch 2 loss==== 0.8326060947933777 accuracy==== 0.72
epoch 3 loss==== 0.8270238572989062 accuracy==== 0.72
epoch 4 loss==== 0.8252993445740644 accuracy==== 0.72
epoch 5 loss==== 0.8250360592190409 accuracy==== 0.7266666666666667
epoch 6 loss==== 0.824935449360947 accuracy==== 0.7266666666666667
epoch 7 loss==== 0.8248721279651884 accuracy==== 0.7266666666666667
epoch 8 loss==== 0.824820061172984 accuracy==== 0.7266666666666667
epoch 9 loss==== 0.8247706801525538 accuracy==== 0.7266666666666667
epoch 10 loss==== 0.8247203724387024 accuracy==== 0.7266666666666667
epoch 11 loss==== 0.8246674264931328 accuracy==== 0.7266666666666667
epoch 12 loss==== 0.8246110605448603 accuracy==== 0.7266666666666667
epoch 13 loss==== 0.8245510382175042 accuracy==== 0.7266666666666667
epoch 14 loss==== 0.8244874607966935 accuracy==== 0.7266666666666667
epoch 15 loss==== 0.8244206169937848 accuracy==== 0.7266666666666667
epoch 16 loss==== 

In [325]:
W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3)
        }
b = {
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3)
        }
        

In [363]:
model.W['W1']

array([[ 7.59235522e-01, -7.84704144e-01,  5.71837816e-01,
        -1.69548853e+00, -5.85873933e-01,  1.70288059e-01,
        -1.72925932e+00,  3.04975290e-01,  3.82538999e-01,
        -1.00599163e+00,  9.84928628e-01, -1.86344060e+00,
        -4.24657732e-01, -9.26831654e-01,  1.17853472e+00,
        -2.03969123e+00, -1.79628440e+00,  3.45658892e-01,
        -1.51111926e+00,  1.40941956e-01,  8.61506684e-01,
        -1.14318468e+00,  1.08871237e+00, -1.36274015e+00,
         1.15523032e+00, -9.03694334e-02,  4.51613964e-01,
         6.53743063e-01, -2.51703458e-01, -3.73974929e-01,
        -1.07879565e-01,  7.35744665e-01, -5.74814808e-01,
         1.91707978e+00, -9.28388761e-01,  8.75678694e-01,
        -8.42582859e-01,  1.28724123e+00, -1.27946223e-01,
        -7.60566551e-01,  2.97489369e-02,  5.20705188e-01,
         1.95425264e-01, -5.18871627e-01,  5.48623885e-01,
         1.53796003e-01,  4.54256349e-01,  1.01408054e+00,
        -1.91817753e+00, -6.94567788e-01,  6.56037800e-0

In [6]:
from sklearn.datasets import load_iris

In [7]:
from tensorflow import keras

In [8]:
import numpy as np

In [12]:
X = load_iris()['data']
y = load_iris()['target']
y = make_onehot(y)

In [ ]:
  def __init__(self):
        self.W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3)
        }
        self.b = {
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3)
        }
        self.Activation ={
            'sigmoid':Activation.sigmoid,
            'relu':Activation.relu,
            'softmax':Activation.softmax
        }

In [10]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(100,activation='relu',input_shape=(4,)))
model.add(keras.layers.Dense(50,activation='relu'))
model.add(keras.layers.Dense(3,activation='softmax'))

In [13]:
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
             metrics=['accuracy'])

In [14]:
%%time
model.fit(X,y,epochs=100,batch_size=150)

Epoch 1/100
1/1 [==============================] - 0s 283ms/step - loss: 1.1674 - accuracy: 0.3333
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 1.1320 - accuracy: 0.3333
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 1.1130 - accuracy: 0.2333
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0987 - accuracy: 0.2067
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 1.0862 - accuracy: 0.2467
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 1.0746 - accuracy: 0.3000
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0639 - accuracy: 0.3267
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0539 - accuracy: 0.3333
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0452 - accuracy: 0.3333
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 1.0377 - accuracy: 0.3333
Epoch 11/100
1/1 [=========

In [46]:
class Multilayer:
    def __init__(self):
        self.x = None
        self.y = None
    
    def forward(self,x,y):
        self.x = x
        self.y = y
        out = self.x * self.y
        return out
    
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx,dy

class Addlayer:
    def __init__(self):
        pass
    
    def forward(self,x,y):
        out = x+y
        return out
    
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx,dy

In [47]:
mul = Multilayer()
add = Addlayer()

In [44]:
mul.forward(100,2)

200

In [45]:
mul.backward(1)

(2, 100)

In [48]:
add.forward(100,10)

110

In [51]:
add.backward(100)

(100, 100)

In [155]:
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        return out
    
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout
        return dx  

class Sigmoid:
    def __init_(self):
        self.out = None
    
    def forward(self,x):
        out = Activation.sigmoid(x)
        self.out = out
        return self.out
    
    def backward(self,dout):
        dx = dout*self.out*(1.-self.out)
        return dx


class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.original_shape = None
        self.dW = None
        self.db = None
        
    def forward(self,x):
        # shape유지
        self.original_shape = x.shape
        x = x.reshape(x.shape[0],-1)
        self.x = x
        out = np.dot(self.x,self.W) + self.b
        return out
        
    
    def backward(self,dout):
        dx = np.dot(dout,self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)
        dx = dx.reshape(*self.original_shape)
        return dx

class SoftmaxWithLoss:
    
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    
    def forward(self,x,t):
        self.t = t
        self.y = Activation.softmax(x)
        self.loss = cross_entropy(self.y,self.t)
        return self.loss
    
    def backward(self,dout=1):
        dx = (self.y - self.t)*dout
        return dx
        
class LeakyReLu:
    
    def __init__(self,alpha=0.01):
        self.alpha = alpha
    
    def forward(self,x):
        out = np.where(x>0,x,self.alpha*x)
        return out
    
    def backward(self,dout):
        dx = np.where(dout >0,dout,self.alpha*dout) 
        return dx

In [147]:
from collections import OrderedDict

In [172]:
class MultiNet:
    def __init__(self):
        self.W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3),
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3),
        }
        self.layers = OrderedDict()
        self.layers['Affine1'] = Affine(self.W['W1'],self.W['b1'])
        self.layers['relu1'] = Relu()
        self.layers['Affine2'] = Affine(self.W['W2'],self.W['b2'])
        self.layers['relu2'] = Relu()
        self.layers['Affine3'] = Affine(self.W['W3'],self.W['b3'])
        self.last_layer = SoftmaxWithLoss()
    
    
    def predict(self,x):
        for layer in self.layers.values():
            x  = layer.forward(x)
        return x
              
    def loss(self,x,t):
        self.y = self.predict(x)   
        return self.last_layer.forward(y,t)
    
    def _numeric_gradient(self,x,t,learning_rate):
        self.learning_rate = learning_rate
        f = lambda w : self.loss(x,t)
        for i in range(len(self.W)):
            self.W['W'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.W['W'+str(i+1)])
            self.b['b'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.b['b'+str(i+1)])
    
    def accuracy(self,x,t):
        result = self.predict(x)
        acc = sum(np.argmax(result,axis=1) == np.argmax(t,axis=1))/len(t)
        return acc
    
    def gradient(self,x,t):
        ## forward
        self.loss(x,t)
        ## backward
        dout = 1
        dout = self.last_layer.backward(dout)
        layers = list(self.layers.values())
        layers.reverse()
        for layer in layers:
            dout = layer.backward(dout)
        grads = {}
        grads['W1'] = self.layers['Affine1'].dW
        grads['W2'] = self.layers['Affine2'].dW
        grads['W3'] = self.layers['Affine3'].dW
        grads['b1'] = self.layers['Affine1'].db
        grads['b2'] = self.layers['Affine2'].db
        grads['b3'] = self.layers['Affine3'].db
        
        return grads
        
        
