In [16]:
import numpy as np
import warnings
from Activations import Activation
warnings.filterwarnings("ignore")

In [2]:
# input_data x1,x2
import numpy as np
x1 = np.random.randint(50,80,10)
x2 = np.random.randint(160,180,10)
X = np.c_[x1,x2]

In [3]:
w1 = np.random.randn(1)
w2 = np.random.randn(1)

In [4]:
out_w1 = w1*x1
out_w2 = w2*x2

In [5]:
out = np.c_[out_w1,out_w2]
out

array([[-120.32044157,  213.27413754],
       [-114.20245302,  210.80854057],
       [-157.0283729 ,  198.48055575],
       [-152.94971386,  203.41174968],
       [-108.08446446,  213.27413754],
       [-146.83172531,  200.94615271],
       [-122.35977109,  198.48055575],
       [-146.83172531,  207.11014513],
       [-134.5957482 ,  210.80854057],
       [-144.79239579,  218.20533147]])

In [6]:
w2

array([1.23279848])

In [30]:
y.reshape(-1,1)

array([[0],
       [0],
       [2],
       [1],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2]])

In [8]:
#one_hot -- keras.utils.to_categorical(data)
y = np.random.randint(0,5,100)

In [9]:
##data
def make_onehot(x):
    col = np.unique(x).size
    row = x.size
    data = np.zeros((row,col))
    for i in np.arange(row):
        data[i,x[i]] = 1
    return data

In [17]:
## 
from sklearn.datasets import load_iris
X = load_iris()['data']
y = load_iris()['target']

In [58]:
X.shape

(150, 4)

In [56]:
y = y.reshape(-1,1)

In [57]:
y.shape

(150, 1)

In [59]:
W = np.random.randn(4,1)
b = np.random.randn(1)

In [60]:
y_hat = np.dot(X,W) + b

In [12]:
## y onehot
y = make_onehot(y)

In [13]:
print(X.shape)
print(y.shape)

(150, 4)
(150, 3)


In [14]:
W = np.random.randn(4,3)
b = np.random.randn(3)

In [15]:
Activation.softmax(np.dot(X,W) + b)

array([[0.91813414, 0.00923423, 0.07263163],
       [0.82588953, 0.03173677, 0.1423737 ],
       [0.88113627, 0.01568035, 0.10318338],
       [0.80247259, 0.01799778, 0.17952963],
       [0.92593924, 0.00635653, 0.06770422],
       [0.94514998, 0.00520696, 0.04964306],
       [0.90223823, 0.00966847, 0.0880933 ],
       [0.88279328, 0.01112281, 0.10608391],
       [0.77275549, 0.0267121 , 0.2005324 ],
       [0.79650449, 0.01924756, 0.18424795],
       [0.93316221, 0.0066051 , 0.06023269],
       [0.84781913, 0.00913405, 0.14304682],
       [0.79868297, 0.02388873, 0.17742831],
       [0.8571773 , 0.01676943, 0.12605328],
       [0.97911213, 0.00382364, 0.01706424],
       [0.98428367, 0.00152101, 0.01419532],
       [0.97430608, 0.00523985, 0.02045406],
       [0.92869978, 0.01106335, 0.06023687],
       [0.93449325, 0.00749221, 0.05801454],
       [0.94386481, 0.00459073, 0.05154446],
       [0.85458297, 0.01508553, 0.13033149],
       [0.94431822, 0.00734783, 0.04833396],
       [0.

In [70]:
x = np.array([1,2,3])
np.exp(x)/np.sum(np.exp(x))

array([0.09003057, 0.24472847, 0.66524096])

In [19]:
def mse(y,t):
    return np.sum((y-t)**2)*0.5

In [20]:
y = np.random.randn(10)
t = np.random.randn(10)
mse(y,t)

7.8376458028469065

In [48]:
def cross_entropy(y,t):
    epsilon = 1e-7
    y = Activation.softmax(y)
    return -np.sum(t*np.log(y+epsilon))/y.shape[0]

In [50]:
y = np.array([1,7,0])
t = np.array([0,1,0])
x1  =cross_entropy(y,t)

In [51]:
y = np.array([2,4,6])
t = np.array([0,0,1])
x2 = cross_entropy(y,t)


In [53]:
def der(f,x):
    h = 1e-7
    fxh = f(x+h)
    fx = f(x)
    return (fxh - fx)/h

In [54]:
f = lambda x:x**2 +2*x

In [59]:
def ff(x,y):
    return x**2 + y**2

In [58]:
der(함수,3)

8.00000009348878

In [75]:
def fx(x):
    return x[0]**2+x[1]**2

In [123]:
def par_der(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x)
        x[idx] = float(tmp_val) - h
        fxh2 = f(x)
        grad[idx] = (fxh1 - fxh2)/(2*h)
        x[idx] = tmp_val
        it.iternext()
    return grad

In [125]:
x = np.array([3.,4.])
par_der(fx,x)

array([6., 8.])

In [134]:
x = np.random.randn(5,6)
it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
while not it.finished:
    x[it.multi_index]
    it.iternext()

In [136]:
def numerical_gradient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        fxh1 = f(x)
        x[idx] = tmp_val - h
        fxh2 = f(x)
        grad[idx] = (fxh1-fxh2)/(2*h)
        x[idx] = tmp_val
        it.iternext()
    return grad

In [137]:
def function_2d(x):
    return x[0]**2+x[1]**2

In [138]:
x = np.array([2.,3.])
function_2d(x)

13.0

In [139]:
numerical_gradient(function_2d,x)

array([4., 6.])

In [140]:
from sklearn.datasets import load_iris

In [141]:
X = load_iris()['data']
y = load_iris()['target']

In [143]:
y = make_onehot(y)

In [154]:
X.shape

(150, 4)

In [155]:
W1 = np.random.randn(4,10)
b1 = np.random.randn(10)
W2 = np.random.randn(10,5)
b2 = np.random.randn(5)
W3 = np.random.randn(5,3)
b3 = np.random.randn(3)

In [206]:
layer1 = np.dot(X,W1) + b1
z1 = Activation.relu(layer1)
layer2 = np.dot(z1,W2) + b2
z2 = Activation.relu(layer2)
layer3 = np.dot(z2,W3) + b3
output = Activation.softmax(layer3)

In [233]:
#cross_entropy(y,output)
loss = cross_entropy
f = lambda w : loss(y,output)
dw = numerical_gradient(f,W1)

In [354]:
class Network:
    
    def __init__(self):
        self.W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3)
        }
        self.b = {
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3)
        }
        self.Activation ={
            'sigmoid':Activation.sigmoid,
            'relu':Activation.relu,
            'softmax':Activation.softmax
        }
        
    
    def predict(self,x):
        result = np.dot(x,self.W['W1']) + self.b['b1']
        for i in range(len(self.W)-2):
            result = np.dot(result,self.W['W'+str(i+2)]) + self.b['b'+str(i+2)]
            result = Activation.relu(result)    
        result = np.dot(result,self.W['W'+str(len(self.W))]) + self.b['b'+str(len(self.W))]    
        return Activation.softmax(result)
    
    def loss(self,x,t):
        self.y = self.predict(x)
        loss = cross_entropy(self.y,t)
        return loss
    
    def gradient(self,x,t,learning_rate):
        self.learning_rate = learning_rate
        f = lambda w : self.loss(x,t)
        for i in range(len(self.W)):
            self.W['W'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.W['W'+str(i+1)])
            self.b['b'+str(i+1)] -= self.learning_rate*numerical_gradient(f,self.b['b'+str(i+1)])
            
        
#     def fit(self,x,t,learning_rate,epochs):
#         for epoch in range(epochs):
#             self.gradient(self,x,t)
        
    
    def accuracy(self,x,t):
        result = self.predict(x)
        acc = sum(np.argmax(result,axis=1) == np.argmax(t,axis=1))/len(t)
        return acc
        

In [355]:
model = Network()
X = load_iris()['data']
y = load_iris()['target']
y = make_onehot(y)

In [356]:
model.loss(X,y)

1.2181110081880455

In [358]:
epochs = 10
for epoch in range(epochs):
    model.gradient(X,y,1e-3)
    print("loss====",model.loss(X,y),"accuracy====",model.accuracy(X,y))

loss==== 1.2181110081880455 accuracy==== 0.3333333333333333
loss==== 1.2181110081880455 accuracy==== 0.3333333333333333
loss==== 1.2181110081880455 accuracy==== 0.3333333333333333
loss==== 1.2181110081880455 accuracy==== 0.3333333333333333
loss==== 1.2181110081880455 accuracy==== 0.3333333333333333
loss==== 1.2181110081880455 accuracy==== 0.3333333333333333


KeyboardInterrupt: 

In [325]:
W = {
            'W1':np.random.randn(4,100),
            'W2':np.random.randn(100,50),
            'W3':np.random.randn(50,3)
        }
b = {
            'b1':np.random.randn(100),
            'b2':np.random.randn(50),
            'b3':np.random.randn(3)
        }
        

In [329]:
for i in b.keys():
    print(i)

b1
b2
b3


In [244]:
import matplotlib.pyplot as plt
plt.plot(np.arange(epochs),loss)

TypeError: float() argument must be a string or a number, not 'method'